login:
    resource: "@loginBundle/Resources/config/routing.php"
    prefix:   /

dashboard:
    resource: "@dashboardBundle/Resources/config/routing.php"
    prefix:   /

site_page:
    resource: "@sitePageBundle/Resources/config/routing.php"
    prefix:   /

