# app/config/security.yml
security:
    firewalls:
        secured_area:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: login
                check_path: login_check
                always_use_default_target_path: true
                default_target_path: /dashboard
            logout:
                path: /logout
                target: /login
    access_control:
        - { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /dashboard, roles: ROLE_ADMINISTRADOR }
    providers:
        usuarios:
            entity: { class: sitePageBundle\Entity\Administrator, property: idadmin }
    encoders:
        sitePageBundle\Entity\Administrator: { algorithm: sha512, encode_as_base64: false, iterations: 1 }
        Symfony\Component\Security\Core\User\User: sha512